# Generated by Django 5.2.7 on 2025-12-05 07:53

import map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=map.models.post_photo_upload_to),
        ),
    ]
