# Generated by Django 5.2.7 on 2025-12-19 04:15

import map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_post_dislike_count_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=map.models.post_photo_upload_to),
        ),
    ]
