# Generated by Django 5.2.7 on 2025-10-30 11:08

import django.db.models.deletion
import journals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude snapshot for quick map rendering.', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude snapshot for quick map rendering.', max_digits=9)),
                ('visit_started_at', models.DateTimeField(blank=True, null=True)),
                ('visit_ended_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('public', 'Public')], default='private', max_length=16)),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('relaxed', 'Relaxed'), ('adventurous', 'Adventurous'), ('romantic', 'Romantic'), ('calm', 'Calm'), ('reflective', 'Reflective'), ('mixed', 'Mixed'), ('custom', 'Custom')], max_length=20)),
                ('mood_custom', models.CharField(blank=True, max_length=60)),
                ('allow_comments', models.BooleanField(default=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=journals.models.journal_cover_upload_to)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary structured data (weather, companions, expenses, etc.).')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JournalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=journals.models.journal_media_upload_to)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='journals.journalentry')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='journals.journaltag'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('formatted_address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('administrative_area', models.CharField(blank=True, max_length=120)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('place_id', models.CharField(blank=True, help_text='External provider identifier (such as Apple Maps or Google).', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='journals.location'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='location_lat_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['created_by'], name='journals_lo_created_c9096a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('created_by', 'name', 'latitude', 'longitude')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['author', 'visibility'], name='entry_author_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['latitude', 'longitude'], name='entry_lat_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['published_at'], name='journals_jo_publish_f46d78_idx'),
        ),
    ]
